name: Integration Tests 🧪
on:
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5.0.0

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@releases/v1
        with:
          token: ${{ secrets.PAT }}
          file: '.github/TEST.md'

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@releases/v1
        with:
          token: ${{ secrets.PAT }}
          file: '.github/TEST.md'
          minimum: 500
          maximum: 999
          marker: 'silver'
          fallback: 'No sponsors at this level'

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@releases/v1
        with:
          token: ${{ secrets.PAT }}
          file: '.github/TEST.md'
          minimum: 1000
          marker: 'gold'
          fallback: 'No sponsors at this level'
